#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'opencontrail-anycast-vip==1.0','console_scripts','opencontrail-anycast-vip'
__requires__ = 'opencontrail-anycast-vip==1.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('opencontrail-anycast-vip==1.0', 'console_scripts', 'opencontrail-anycast-vip')()
    )
