#!/bin/sh
### BEGIN INIT INFO
# Provides:          opencontrail-anycast-vip
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: fast and reliable anycast VIP manager for opencontrail controllers
# Description:       This file should be used to start and stop opencontrail-anycast-vip.
### END INIT INFO

# Author: Sanju Abraham <sanjua@juniper.net>

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
PIDFILE=/var/run/opencontrail-anycast-vip/opencontrail-anycast-vip.pid
CONFIG=/etc/opencontrail-anycast-vip/opencontrail-anycast-vip.conf
DAEMON=/usr/local/bin/opencontrail-anycast-vip
DAEMON_ARGS="--conf_file $CONFIG"
OPENCONTRAIL_ANYCAST_VIP='/usr/local/bin/opencontrail-anycast-vip'
RUNDIR=/var/run/opencontrail-anycast-vip
EXTRAOPTS=

test -x $DAEMON || exit 0

if [ -e /etc/default/opencontrail-anycast-vip ]; then
	. /etc/default/opencontrail-anycast-vip
fi

test -f "$CONFIG" || exit 0

[ -f /etc/default/rcS ] && . /etc/default/rcS
. /lib/lsb/init-functions

check_anycastvip_config()
{
        if [ ! -f "$CONFIG" ] ; then
		log_end_msg 1
		exit 1
	fi
}

anycastvip_start()
{
	[ -d "$RUNDIR" ] || mkdir "$RUNDIR"
	chown root:root "$RUNDIR"
	chmod 2775 "$RUNDIR"

	check_anycastvip_config

        #$DAEMON $DAEMON_ARGS > /dev/null 2>&1 & 
        start-stop-daemon --start --pidfile "$PIDFILE" --background --oknodo \
                --exec $DAEMON -- $DAEMON_ARGS \
                $EXTRAOPTS || return 2

	return 0
}

anycastvip_stop()
{
	if [ ! -f $PIDFILE ] ; then
		# This is a success according to LSB
		return 0
	fi
	for pid in $(cat $PIDFILE) ; do
		/bin/kill $pid || return 4
	done
	rm -f $PIDFILE
	return 0
}

anycastvip_status()
{
	if [ ! -f $PIDFILE ] ; then
		# program not running
		return 3
	fi

	for pid in $(cat $PIDFILE) ; do
		if ! ps --no-headers p "$pid" | grep opencontrail-anycast-vip > /dev/null ; then
			# program running, bogus pidfile
			return 1
		fi
	done

	return 0
}


case "$1" in
start)
	log_daemon_msg "Starting opencontrail-anycast-vip"
	anycastvip_start
	ret=$?
	case "$ret" in
	0)
		log_end_msg 0
		;;
	1)
		log_end_msg 1
		echo "conf file '$CONFIG' not found, opencontrail-anycast-vip not started."
		;;
	2)
		log_end_msg 2
		;;
	esac
	exit $ret
	;;
stop)
	log_daemon_msg "Stopping opencontrail-anycast-vip"
	anycastvip_stop
	ret=$?
	case "$ret" in
	0|1)
		log_end_msg 0
		;;
	2)
		log_end_msg 1
		;;
	esac
	exit $ret
	;;
restart)
	log_daemon_msg "Restarting opencontrail-anycast-vip"
	anycastvip_stop
	anycastvip_start
	ret=$?
	case "$ret" in
	0)
		log_end_msg 0
		;;
	1)
		log_end_msg 1
		;;
	2)
		log_end_msg 2
		;;
	esac
	exit $ret
	;;
status)
	anycastvip_status
	ret=$?
	case "$ret" in
	0)
		echo "opencontrail-anycast-vip is running."
		;;
	1)
		echo "opencontrail-anycast-vip dead, but $PIDFILE exists."
		;;
	*)
		echo "opencontrail-anycast-vip not running."
		;;
	esac
	exit $ret
	;;
*)
	echo "Usage: /etc/init.d/opencontrail-anycast-vip {start|stop|reload|restart|status}"
	exit 2
	;;
esac

:
